baseURL = "https://alphabytez.github.io/STING-CE-Docs/"
title = "STING Documentation"
languageCode = "en-us"
contentDir = "content/en"
defaultContentLanguage = "en"
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
enableGitInfo = true

# Make relative URLs absolute with baseURL
canonifyURLs = true

# Docsy theme via Hugo Modules
[module]
  # Import Docsy theme modules FIRST
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

  # Then override with project files
  [[module.mounts]]
    source = "content/en"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "monokai"
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Site params
[params]
  copyright = "AlphaBytez"
  privacy_policy = "https://alphabytez.dev/privacy"

  # STING Branding
  description = "Bee Smart. Bee Secure."

  # Logo and Favicon
  favicon = "favicon.svg"

  # Custom logo configuration
  [params.logos]
    navbar = "images/sting-logo.webp"

  # GitHub repo for "Edit this page" links
  github_repo = "https://github.com/AlphaBytez/STING-CE-Docs"
  github_project_repo = "https://github.com/AlphaBytez/STING-CE-Docs"
  github_branch = "main"

  # Search configuration - use Algolia DocSearch
  algolia_docsearch = true
  offlineSearch = false

  # Algolia DocSearch configuration
  [params.search.algolia]
    appId = "YOUR_APP_ID"
    apiKey = "YOUR_SEARCH_API_KEY"
    indexName = "sting-docs"

  # Enable version dropdown
  version_menu = "Versions"
  version = "v1.0"
  url_latest_version = "https://alphabytez.github.io/STING-CE-Docs/docs/"

  [[params.versions]]
    version = "v1.0 (latest)"
    url = "https://alphabytez.github.io/STING-CE-Docs/docs/"

  # UI customization
  [params.ui]
    sidebar_menu_compact = true
    sidebar_menu_foldable = true
    breadcrumb_disable = false
    sidebar_search_disable = false
    navbar_logo = true
    footer_about_enable = true
    navbar_translucent_over_cover_disable = false

    # Sidebar menu levels to show
    ul_show = 1

    # Color theme - light/dark mode
    [params.ui.feedback]
      enable = true
      yes = 'Glad to hear it! Please <a href="https://github.com/AlphaBytez/STING-CE-Docs/issues/new">tell us how we can improve</a>.'
      no = 'Sorry to hear that. Please <a href="https://github.com/AlphaBytez/STING-CE-Docs/issues/new">tell us how we can improve</a>.'

    [params.ui.readingtime]
      enable = true

  # Links in footer
  [params.links]
    [[params.links.user]]
      name = "GitHub Discussions"
      url = "https://github.com/AlphaBytez/STING-CE-Public/discussions"
      icon = "fab fa-github"
      desc = "Discussion and help from the community"
    [[params.links.user]]
      name = "Email Support"
      url = "mailto:olliec@alphabytez.dev"
      icon = "fa fa-envelope"
      desc = "Get in touch with the team"

    [[params.links.developer]]
      name = "Docs GitHub"
      url = "https://github.com/AlphaBytez/STING-CE-Docs"
      icon = "fab fa-github"
      desc = "Documentation repository"
    [[params.links.developer]]
      name = "STING GitHub"
      url = "https://github.com/AlphaBytez/STING-CE-Public"
      icon = "fab fa-github"
      desc = "Main STING repository"
    [[params.links.developer]]
      name = "Marketing Site"
      url = "https://AlphaBytez.github.io/sting-website/"
      icon = "fa fa-globe"
      desc = "Visit our marketing site"

# Menu configuration
[[menu.main]]
  name = "Documentation"
  weight = 10
  url = "/docs/"

[[menu.main]]
  name = "API Reference"
  weight = 20
  url = "/api/"

[[menu.main]]
  name = "About"
  weight = 30
  url = "/about/"

[[menu.main]]
  name = "GitHub"
  weight = 40
  url = "https://github.com/AlphaBytez/STING-CE-Public"
  pre = "<i class='fab fa-github'></i>"

# Configure how URLs look
[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

# Services configuration
[services]
  [services.googleAnalytics]
    # Uncomment and add your GA ID when ready
    # id = "UA-00000000-0"

# Privacy configuration
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.x]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Taxonomy configuration
[taxonomies]
  tag = "tags"
  category = "categories"

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
